# -*- coding: utf-8 -*-
"""COVID-19 Data Analysis & Dashboard System

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dIbdiUTcMW-Ultvt-BNpEBP2Icfxc8YS
"""

import pandas as pd
import zipfile

zip_file_path = "/content/sample_data/archive (2).zip"
csv_file_in_zip = "country_wise_latest.csv"

with zipfile.ZipFile(zip_file_path, 'r') as z:
    with z.open(csv_file_in_zip) as f:
        df = pd.read_csv(f)

df = df.drop(columns=[
    'Province/State', 'Lat', 'Long_',
    'Last Update', 'Incident_Rate', 'Case_Fatality_Ratio'
], errors='ignore')

print(df.head())

"""# Data Cleaning & Preprocessing"""

print(df.isnull().sum())
df = df.fillna(0)
cols = ['Confirmed', 'Deaths', 'Recovered', 'Active']
df[cols] = df[cols].apply(pd.to_numeric, errors='coerce')
df = df.drop_duplicates()

"""# Descriptive Statistics"""

total_confirmed = df['Confirmed'].sum()
total_deaths = df['Deaths'].sum()
total_recovered = df['Recovered'].sum()

print("Total Confirmed:", total_confirmed)
print("Total Deaths:", total_deaths)
print("Total Recovered:", total_recovered)

print(df.describe())

"""# Country-Based Analysis"""

top_countries = df.sort_values(by='Confirmed', ascending=False).head(10)
print(top_countries[['Country/Region', 'Confirmed', 'Deaths', 'Recovered']])

"""# Relationship Analysis"""

corr = df[['Confirmed', 'Deaths', 'Recovered', 'Active']].corr()
print(corr)

"""# Dashboard"""

import plotly.express as px
import pandas as pd
!pip install dash
from dash import Dash, dcc, html, Input, Output

app = Dash(__name__)

countries = df['Country/Region'].unique()

app.layout = html.Div([
    html.H1("COVID-19 Dashboard", style={'textAlign': 'center'}),
    dcc.Dropdown(
        id='country',
        options=[{'label': c, 'value': c} for c in countries],
        value=countries[0]
    ),

    dcc.Graph(id='bar'),
    dcc.Graph(id='pie'),
    dcc.Graph(id='scatter'),
    dcc.Graph(id='heatmap')
])
print(dcc.Graph)

"""# Callback"""

@app.callback(
    [Output('bar', 'figure'),
     Output('pie', 'figure'),
     Output('scatter', 'figure'),
     Output('heatmap', 'figure')],
    [Input('country', 'value')]
)
def update(selected_country):

    filtered = df[df['Country/Region'] == selected_country]

    top = df.sort_values(by='Confirmed', ascending=False).head(10)
    bar = px.bar(top, x='Country/Region', y='Confirmed',
                 title="Top Affected Countries")
    row = filtered.iloc[0]
    pie = px.pie(
        names=['Confirmed', 'Deaths', 'Recovered', 'Active'],
        values=[row['Confirmed'], row['Deaths'], row['Recovered'], row['Active']],
        title="Case Distribution"
    )
    scatter = px.scatter(df, x='Confirmed', y='Deaths',
                         title="Confirmed vs Deaths")
    heatmap = px.imshow(corr, text_auto=True,
                        title="Correlation Heatmap")

    return bar, pie, scatter, heatmap

if __name__ == '__main__':
    app.run(debug=True, port=8051)

high_risk = df.sort_values(by='Deaths', ascending=False).head(5)
print("High Risk Countries:\n", high_risk[['Country/Region', 'Deaths']])
df['Recovery Rate'] = df['Recovered'] / df['Confirmed'].replace(0, 1)
print("Average Recovery Rate:", df['Recovery Rate'].mean())

"""# Line chart"""

top = df.sort_values(by='Confirmed', ascending=False).head(10)

fig_line = px.line(top,
                   x='Country/Region',
                   y='Confirmed',
                   markers=True,
                   title="Top Countries - Confirmed Cases")

fig_line.show()

"""# Bar chart"""

import plotly.express as px
top = df.sort_values(by='Confirmed', ascending=False).head(10)

fig_bar = px.bar(top,
                 x='Country/Region',
                 y='Confirmed',
                 title="Top 10 Affected Countries")

fig_bar.show()

"""# Pie chart"""

row = df.iloc[0]

fig_pie = px.pie(
    names=['Confirmed', 'Deaths', 'Recovered', 'Active'],
    values=[row['Confirmed'], row['Deaths'], row['Recovered'], row['Active']],
    title=f"Case Distribution - {row['Country/Region']}"
)

fig_pie.show()

"""# Scatter plot"""

fig_scatter = px.scatter(df,
                         x='Confirmed',
                         y='Deaths',
                         size='Confirmed',
                         hover_name='Country/Region',
                         title="Confirmed vs Deaths")

fig_scatter.show()

"""# Heatmap"""

corr = df[['Confirmed', 'Deaths', 'Recovered', 'Active']].corr()

fig_heatmap = px.imshow(corr,
                        text_auto=True,
                        title="Correlation Heatmap")

fig_heatmap.show()